// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCaptureStats() {
  return window['go']['backend']['App']['GetCaptureStats']();
}

export function GetInterfaces() {
  return window['go']['backend']['App']['GetInterfaces']();
}

export function GetPackets() {
  return window['go']['backend']['App']['GetPackets']();
}

export function GetPingResults(arg1) {
  return window['go']['backend']['App']['GetPingResults'](arg1);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function StartCapture(arg1, arg2) {
  return window['go']['backend']['App']['StartCapture'](arg1, arg2);
}

export function StartPing(arg1, arg2) {
  return window['go']['backend']['App']['StartPing'](arg1, arg2);
}

export function StopCapture() {
  return window['go']['backend']['App']['StopCapture']();
}

export function StopPing(arg1) {
  return window['go']['backend']['App']['StopPing'](arg1);
}

export function TestTCPConnection(arg1, arg2, arg3) {
  return window['go']['backend']['App']['TestTCPConnection'](arg1, arg2, arg3);
}
